---
title: Book Summary - Deep Work by Cal Newport
subtitle: The Ultimate Toolkit for Publishing?
description: Testing Pandoc's org to HTML compilation.
tags: emacs, haskell
created: 2016-07-13
modified: 2016-07-14
status: finished
confidence: log
importance: 1
---

** In the new economy with rapid growth in technology, there are 3 groups with massive advantages
   1. Those who can work well and creatively with intelligent machines (high-skilled workers)
   2. Those who are the best at what they do (superstars)
   3. Those with access to capital (owners)
** 2 abilities for thriving in the new info-winners-take-all economy
   1. The ability to quickly master hard things
   2. The ability to produce at an elite level, in terms of both quality and speed
 These two are enhanced greatly by maximizing deep work time and its
 intensity.
** *Definition*
*** Deep work:
 Professional activities performed in a state of distraction-free concentration that push your cognitive capabilities to their limit.
 These efforts create new value, improve your skill, and are hard to replicate.
*** Shallow work:
 Non-cognitively demanding, logistical-style tasks, often performed while distracted. 
 These efforts tend not to create much new value in the world and are easy to replicate.
*** How to recognize deep work vs shallow work?
 Ask yourself this: How long would it take (in months) to train a smart
 recent college graduate with no specialized training in my field to
 complete this task?

 Anything less than 3 months is definitely on the shallow end.

** The Rules:
   1. Decide on your deep work schedule type
     1. x consecutive days in a week or month of all-days deep work
     2. x hours every day of deep work (in the morning)
     3. x hours every day (can switch focus at will)
   2. Ritualize it. Have triggers. Enforce a fixed x hours. Then just don't do it at all for the rest of the day
   3. Downtime is essential for optimal schedule. At the end of workday, shut down all your work action/thoughts. say “Shutdown complete"
   4. Embrace boredom. Train your brain *not* to act on your first desire for novelty.
   5. Quit Social Media. Or check it just once per day.
   6. Work at a fixed 8 hours per day to “Drain the shallow” out of life. we will have time only for deep work.
