---
title: Book Summary - Thinking - fast and slow
subtitle: None
description: None
tags: summary, thinking
created: 2014-02-04
published: 2014-12-15
status: draft
confidence: log
importance: 1
---
** Part I. Two systems

*** Overview

System 1 operates automatically and quickly, with little or no effort and conscious control.

System 2 uses attention and demands effort. Slow and orderly.

*System 1 examples* - Detect moving objects, complete familiar phrases, Detect/recognize random sounds.

*System 2 examples* - Mental 2+ digits multiplication, focus on voice of one person in a crowded room.

Experts often have vast and varied experiences in specific domain such that they have the right "intuition". Example - firefighter avoiding death​traps or chess master's "checkmate in 5 moves".

System 1&2 are fictitious caharcters, handy mental Models. They don't actually exist as separate entities in the brain.

The best we can do with these 2 systems is a compromise: learn to recognize situations in which biases/mistakes are likely. Then System 2 is engaged to avoid them.

*** Attention and Effort

Pupil dilation is an indicator of mental effort and engagement -- A window to your soul.

As a person becomes skilled in tasks, the demand for effort (energy) diminishes -- with fewer brain regains involved. (Chunking into habits?)

Talent has similar effects. Highly intelligent (IQ?) Individuals need less effort to solve same problems.

What is effortful?
    - Adoption and termination of new task sets. (Never seen nor tried before)
    - Switching from one task to another. Note: both 1. And 2. are mindful tasks.
    - Constantly using Working memory to the fullest.


*** The Lazy Controller

Ego Depletion - brain is running on limited fuel called glucose. Manage
them carefully. System 1 uses a lot more energy, so the brain will
switch to System 2 (indulgence) when depleted.

*** Associative Machine

Priming - system 1 has associative memory which triggers continuously and unconsciously. Everyone is susceptible.

Priming effect is small but robust. It has the most impact when you are uncertain or not thinking much (due to habit or time-to-decisions). The effect depends on recent events - time series of short term
memory.

This means that society, environment and social group can affect your mood and thoughts, beware!

Ideomotor effect = previous actions (like walking slowing) prime your thoughts unconsciously (old age)

*** Cognitive Ease

Familiarity/ease -> system 1 engages = more accepting/gullible

Unfamiliar -> system 2 engages = doubtful/critical

Mere exposure effect - Repetition induces cognitive ease and feeling of familiarity. This works even on subconscious level as it impacts System 1 directly.

How to communicate persuasively - do it in a way that REDUCES cognitive strain and put System 1 at ease.
1. Use clear, legible font. Color: black, red, blue.
2. Use simple, concise words. Put the work on the encoder not the decoder.
3. Make it memorable, put it in verses if you can.
4. If you quote a source, choose easy to pronounce names.

System 1 is doing greedy search, therefore good at positive and one-sided affirmation. something like an excuse machine too. if we ask it "why?", it will come up with a reason.

System 1 is gullible and biased to believe,

System 2 is in charge of doubting and unbelieving.


Halo effect - 1st impression biases your view of the whole thing. Order of information consumed matter! For example: Susan is friendly.  Is she charitable? (System 1: probably yes!)

One - sided effect - System 1 always weave a stpry and jump to conclusion with available data, no matter the quality and quantity. Be especially CAREFUL when being presented with one sided information.

System 2 directs attention and searches memory to find answers. System 2 does basic assessments computation continuously. Here's some examples.

-  safety & familiarity - good mood and cognitive ease when meeting friends instead of strangers on the street. Under 1 sec recognition.
-  Dominance & competency - square jaw and confident smile. Best Politician = strong chin + slight confident smile.
-  Sets & prototypes - system 1 do well on estimating averages but badly on sums. 100 vs 10k People died  = same effect.
-  Value intensity across dimensions - "how r all is a man who is as tall as Julie was intelligent? "
