---
title: Book Summary - Early Retirement Extreme by Jacob Fisker
subtitle: Financial Independence
description: None
tags: FI, antifragile
created: 2016-12-03
published: 2020-08-30
status: draft
confidence: log
importance: 1
---

** The lock-in
- Mass delusion of spending money = one sign of success
- Comparison of delusion with [[https://en.wikipedia.org/wiki/Allegory_of_the_Cave][Plato's cave]]
 - common life track: school -> university -> career. not so efficient.
 - cost of specialization (degrees/career): fragile to change. generalists fare better.
 - corporate ladder is more like a pyramid. survivorship bias.
- The problem with personal finance
 - cash flow problem: one stream of (stable?) income, many debt.
 - consumer debt, unlike business debt, does not generate income.
  - major consumer debt means borrowing from the future, where income is uncertain.
 - saving rate close to zero. (probably U.S. specifically)
- retirement: a relatively new phenomenon in 20th century.
 - most common early retirement resembles long vacation. a net negative in society productivity. (spending past accumulated wealth?)
- breaking out of "the lock-in"
 - reduce waste and increase efficiency. (lower-cost living with same benefits)
 - invest the gain (from waste reduction) in businesses
 - find something meaningful to do instead of work.

** Economic degrees of freedom
To understand a system, it is helpful to identify degrees of freedom and constraints.

- we will use this economic "coupling" graph for analysis
 - horizontal axis: *coupling* from loose to tight. loosely coupled system is less likely to fail.
 - vertical axis: *organization* from linear to non-linear. non-linear feedbacks will have affect on input -> output. (convex payoff)
- there are mainly 4 archetypes of a working person. for each group, the "norm" behavior/culture is different.
 - *salary man* (tight/linear): fragile to business change, rewards (less than) linearly scale with efforts. 
  - have options, but do not create options.
  - both work and consumption are well-controlled. eg. cog in the machine.
  - one income --> all consumption
 - *working man* (loose/linear): (freelancers etc.) uncertain income, but less fragile. linear rewards.
  - often have emergency fund due to uncertainty of cash flow, which makes them more anti-fragile.
  - has many clients, unlike one big client per salary man.
  - consumer pattern similar to salary man.
 - *business man* (tight/non-linear): owns one or more business.
  - personal cash flow is minimal compared to business cash flow they controlled.
  - tight coupling to one or few businesses. convex payoff.
  - job is find solution to problems, relying on assets and other people.
  - need to quickly solve things, due to competition.
 - *renaissance man* (loose/non-linear): a combination of those 3 types.
  - competent in variety of fields, can take on full-time job as needed.
  - also a generalist, many vocational skills to pickup work based on supply/demand.
  - has vast knowledge and experience in solving complex problems efficiently, therefore can do in-sourcing of many things (doing tax, repairs, painting house, cooking) which reduces cash outflows considerably.
  - potentially has assets and investments in various type of businesses.
  - In a sense, a person do can make/do anything. a local leader and inspiration to other people.
- Succession and cycle of change: one type is more popular at certain stage
 - each "species" is adapted to thrive in a very specific environment
 - if the conditions change, the existing species will be outcompeted by a species which is better adapted to new ones.
 - Succession occurs because the dominance of one species gradually changes the environment.
- Ergodicity and destiny
 - [[https://www.barbellstrategy.com/blog/post-9mwgp-gw568][What is ergodicity?]]: The simple statement is that the space average is the same as the time average. Which means that if you look at one point over time you’ll get the same answer if you look at all of space at one time. 
 - However, what Jacob mean by using ergodicity is slightly different: with certain set of behaviors, over time, that species will end up where it "deserves". luck will play a part in short term, but not long term.
 - Therefore, to achieve any kind of long-term goals/outcomes, we need to have *agency* to follow a set of behaviors -- either by habit or sheer willpower -- over a period of time.
 - Agency is the attitude that any problem can be fixed, given enough resources in the form of time, effort, and determination. Agency is generally transferable to different fields. To build agency, it is recommended to grit through something that is considered very difficult, at least once in your life.
 - Our current world: climax stage
  - We have an economic model that is based on pulling resources out of the ground, turning them into unnecessary products, getting people to buy them, then getting people to throw those away for newer products. this kind of GDP is not sustainable.

** The Renaissance ideal
- Human capital and necessary personal assets
  - Physiological
    - maintain optimal levels of physical and mental health
    - know how the human body functions and physiologically adapts to imposed demands like stress, overeating, lack of exercise, and their opposites
    - know why and which kinds of food promote health and which kinds destroy health
    - maintain good habits. know how to preserve food and how to tesll when food is spoiled.
    - be able to compete in local sports competitions.
    - be able to perform physically while exhausted, hungry, or tired. Test: carrying an unconscious person out of a burning house, or pulling oneself up and hanging from a gutter.
    - know at least basic first aid
  - Intellectual
    - be able to prioritize the relevance of information and be able to quickly research and find relevant information in many different areas. Learn independently and have an interest in doing so.
    - have enough generalized knowledge to be able to understand the information and put it into the context of a mental framework, a model or a procedure, and use it to ask further questions.
    - recognize which problems the model applies to, take the solution to one problem, generalize it, and apply it to another problem.
    - be able to critically analyze the model, refine it, and combine different models to achieve an objective. Practice critical thinking in all aspects of life to reach a degree of rational certainty. Be open to new ideas but do not accept anything without examination.
    - synthesize interdiscilinary information and laterally connect similarities which are not immediately apprent, discovering new models and precedures.
    - evaluate different methods, models, and precedures while effectively ranking them for utility, and piking the best one while recognizing the pertinence of other methods. Pursue relevant and correct knowledge persistently and consistently. Master the fundamentals.
  - Economic
    - understand the difference between price and value. Value is psychological, price is determined by the market.
    - learn to consider more than the immediate consequences of a choice. Also consider the future consequences -- for example, opportunity cost and time-value of money. Learn to see the unseen.
    - learn to consider more than the consequences of a choice for just one group of people, but for all others as well.
    - realize tha economic agents all represent special interests that typically interpret the situation according to their own interests or political views.
    - understand the difference between assets and liabilities. Understand leveragte and cash flows. In particular, learn what is an investment (an income generating asset) and what is not an investment (items for personal use).
    - know the law of supply and demand, the difference between savings and investments, and the difference between present and future value.
    - understand how the stock, bond, and/or real estate markets work, both in theory and practice.
    - be able to do your own tax return, make a budget, and balance a checkbook.
  - Emotional
    - be able to appraise value in all matters to make sound decisions.
    - not waste time, money, effort, or resources.
    - not be subject to emotional manipulation or egage in wishful, magical thinking, believing things are true because he would like them to be true -- or worse, believing he can influence external events by thinking positively about them.
    - have a strong character, persist, cope with adversity, be resistant to stress, be calm, and displace frustration.
    - develop a passion, appreciate the arts and what it means to be human, rather than just a "human resource".
    - be empathetic and understand that people and situations are complex.
    - make social connections and increase the value of interpersonal relationships.
    - be able to patiently await a better solution and be willing to compromise and accept something that is close, but not exactly your ideal.
  - Social
    - get to know people outside your profession, hobby/club, religion, political party, socioeconomic stratum, country.
    - start or join a co-op. This can be anything from buying groceries to participating in a tool shop, to sharing movies with other people.
    - learn how to sell, barter, swap, and give things away.
    - learn how to network and build your social capital.
    - get involved in politices on some level.
  - Technical
    - have knowledge of the skills of different professions to be able to critically judge the services of professionals.
    - have a working understanding of all the techonology you use to understand its limits and benefits.
    - learn how to select the optimal tools for your use, how to maintain them, and how to repair them when they break down.
    - learn a common trade to be able to barter your skills for other things.
  - Ecological
    - know the name of 5 grasses, 5 birds, 5 trees, etc. local to your area, and be able to recognize them.
    - know which food is in season and how much oil, water, and fertilizer it takes to grow/raise the food (out of season, out of location) and how it is sensitive t o Liebig's Law of the minimum.
    - grow and sustain a garden without using pesticides, hybrid seeds, chemical-based fertilizer, etc. A garden and indeed any system will achieve maximum integrity when it is in balance, and when growth is stable and resilient without ongoing external interference.
    - promote functional diversity to retain adaptive capacity, to allow evolution to happen when the environment changes. Adaptive and evolutionary potential should be considered before interfering. Action always have reactions, and so action is not always a good idea.
    - always consider the system and understand both the parts and the whole. No parts exist without the whole and the whole doesn't exist without the parts. Everything is related to everything else, mostly indirectly. Thus, changing one part will change the whole.
    - recognize multiple bottom lines, flows, and balances in terms of primary, secondary, and tertiary consumers, producers, and decomposers.
    - use the maximum power principle, which states that systems srive to maximize the rate of useful work -- that is, to not waste energy to its environment.
    - understand the concept of characteristic scales in terms of change and the effect of limits on competition and cooperation. Understand the difference between positive feedbakcs and negative feedbacks (both are needed) and how linking feedbacks lead to cycles, runaways, or overshoots.
    - study the structure and principles of different systems to build a collection of models, in order to understand other systems.
- The Renaissance education
  - Fundamental principles, concepts, or structures are more important than specific techniques, because it is always applicable to other fields.
  - People remember most of what they do, some of what they say, but little of what they see or hear. It's therefore important to do things. In cooking, try to leave ingredients out or substitute in new ones to see what happens. In sports, practice unmastered techniques acticely and put them together with other techniques. In finance, try investing in different things.
- Gauging mastery
  - one method is using tenure (time spent). 1k hours to Journeyman, 10K hours to Expert.
  - Copying -> Comparing -> Compiling (collecting) -> Computing (pairing) -> Coordinating (refining) -> Creating (synthesis)
- Decoupling and increasing complexity
  - increasing complexity means higher capability, often at the cost of higher maintenance / lost of responsiveness to change.
  - simplicity, often by decoupling several joined variables, make the system more predictable and easier to maintain/change. An even better way is to use abstractions (lossless compression) to maintain capability and simplify systems.
  - complex systems, if designed well, are more resilient thatn simple systems.
  - work switch has cost, depending on the nature of work. (Managers vs Hackers)

** Strategy, tactics, and guiding principles
- Plan vs Strategy
 - A plan is a string of action (follow certain path)
 - A strategy is a web of actions (consider multiple path, take optimal steps, then reevaluate -- multi-arm bandits)
- Strategic principles
- Tactical principles



