---
title: Book Summary - How Economic Machine Works by Ray Dalio
subtitle: None
description: None
tags: economics
created: 2015-01-19
published: 2017-11-26
status: draft
confidence: log
importance: 1
---


An economy is simply a sum of transaction. A market is sum of transactions for the same thing (ex: wheat, gold, property)

A transaction consists of a buyer giving money or credit to a seller in exchange of goods, services, or financial assets.

For any market or economy, if we know the total amount of money (or credit) spent, and the total quantity sold, then we know everything needed to understand it.

Price = Total money or credit รท total quantity sold.

All changes economic activity are due to change money/credit or quantity. The money/credit part is much easier to change.

** Buyer segment:
  -  Private
    -  households
    -  businesses
        -  domestic
        -  foreign
  -  Government
    -  Federal Govt
    -  Central bank (money creator)

** Three Big Forces that impact economy.
  1. Long term productivity growth (about 2% per year) - straight line up
  2. Long-term debt cycle (deleveraging and redistribution of wealth) -
    lower frequency sine wave
  3. Short-term debt cycle (business cycle) - higher frequency sine wave

