---
title: Book Summary - Early Retirement Extreme by Jacob Fisker
subtitle: Financial Independence
description: None
tags: FI, antifragile
created: 2016-12-03
published: 2019-02-26
status: draft
confidence: log
importance: 1
---

** The lock-in
- Mass delusion of spending money = one sign of success
- Comparison of delusion with [[https://en.wikipedia.org/wiki/Allegory_of_the_Cave][Plato's cave]]
 - common life track: school -> university -> career. not so efficient.
 - cost of specialization (degrees/career): fragile to change. generalists fare better.
 - corporate ladder is more like a pyramid. survivorship bias.
- The problem with personal finance
 - cash flow problem: one stream of (stable?) income, many debt.
 - consumer debt, unlike business debt, does not generate income.
  - major consumer debt means borrowing from the future, where income is uncertain.
 - saving rate close to zero. (probably U.S. specifically)
- retirement: a relatively new phenomenon in 20th century.
 - most common early retirement resembles long vacation. a net negative in society productivity. (spending past accumulated wealth?)
- breaking out of "the lock-in"
 - reduce waste and increase efficiency. (lower-cost living with same benefits)
 - invest the gain (from waste reduction) in businesses
 - find something meaningful to do instead of work.

** Economic degrees of freedom
To understand a system, it is helpful to identify degrees of freedom and constraints.

- we will use this economic "coupling" graph for analysis
 - horizontal axis: *coupling* from loose to tight. loosely coupled system is less likely to fail.
 - vertical axis: *organization* from linear to non-linear. non-linear feedbacks will have affect on input -> output. (convex payoff)
- there are mainly 4 archetypes of a working person. for each group, the "norm" behavior/culture is different.
 - *salary man* (tight/linear): fragile to business change, rewards (less than) linearly scale with efforts. 
  - have options, but do not create options.
  - both work and consumption are well-controlled. eg. cog in the machine.
  - one income --> all consumption
 - *working man* (loose/linear): (freelancers etc.) uncertain income, but less fragile. linear rewards.
  - often have emergency fund due to uncertainty of cash flow, which makes them more anti-fragile.
  - has many clients, unlike one big client per salary man.
  - consumer pattern similar to salary man.
 - *business man* (tight/non-linear): owns one or more business.
  - personal cash flow is minimal compared to business cash flow they controlled.
  - tight coupling to one or few businesses. convex payoff.
  - job is find solution to problems, relying on assets and other people.
  - need to quickly solve things, due to competition.
 - *renaissance man* (loose/non-linear): a combination of those 3 types.
  - competent in variety of fields, can take on full-time job as needed.
  - also a generalist, many vocational skills to pickup work based on supply/demand.
  - has vast knowledge and experience in solving complex problems efficiently, therefore can do in-sourcing of many things (doing tax, repairs, painting house, cooking) which reduces cash outflows considerably.
  - potentially has assets and investments in various type of businesses.
  - In a sense, a person do can make/do anything. a local leader and inspiration to other people.
- Succession and cycle of change: one type is more popular at certain stage
 - each "species" is adapted to thrive in a very specific environment
 - if the conditions change, the existing species will be outcompeted by a species which is better adapted to new ones.
 - Succession occurs because the dominance of one species gradually changes the environment.
- Ergodicity and destiny
 - 

** Plan vs Strategy
  -  A plan is a string of actions. One action fail, all fail. Fragile.
  -  A strategy is a web of actions. can't go this way then go another
    way. it means having logical constraints in your head (similar to
    numerical programming) which exposes you to a set of path you can
    choose to execute (and diverge later as long as the new path satisfies
    the constraints)
