---
title: Book Summary - Navy Seal Fitness Guide
subtitle: None
description: fitness
tags: fitness
created: 2020-08-13
published: 2020-08-15
status: draft
confidence: log
importance: 1
---

[[https://www.usuhs.edu/sites/default/files/media/mem/pdf/navysealfitnessguide.pdf][Original link to guide in PDF here.]]

** Note : Navy Seal physical screening test
- Swim 500 yards (457 m.) in 12.5 minutes or less
- Rest 10 minutes
- Do 42 push-ups in under 2 minutes
- Rest 2 minutes
- Do 50 sit-ups in under 2 minutes
- Rest 2 minutes
- Do 6 pull-ups in under 2 minutes
- Rest 10 minutes
- Run 1.5 miles (2.4 km) in boots and long pants in less than 11.5 minutes

** Chapter 1: Overview of Physical Fitness
- Navy-seal fitness components (look up definition in PDF)
  - Skill-related: Agility, Balance, Coordination, Speed, Power, Reaction time
  - Health-related: Cardiorespiratory endurance, Muscular endurance, Muscular strength, Body composition, Flexibility
- Of the three muscle types (Cardiac, Skeletal, Smooth), we will only focus on skeletal muscle:

    The proportion of muscle types depends on genetics at birth. However, all can be improved by endurance and power training.
   
  - Slow Twitch Oxidative (Type I) -- aerobic, slow but long, for endurance
  - Fast Twitch Oxidative-Glycolytic (Type IIa) -- semi-aerobic, middle place
  - Fast Twitch Glycolytic (Type IIb) -- anaerobic, fast but short-lived. glycogen as fuel = fatigue easily.
- Principles of Physical training
  - Overload: training at higher level than usual until body adapts to new level. aerobic training = 70%-90% of Max Heart Rate (HR) or at 130-170 HR (age 35)
  - Specificity: training that focuses on achieving certain task. swimming vs running etc.
  - Individual Differences: same program, difference responses per person
  - Detraining: need to keep regular exercises to maintain fitness. FITT = Frequency, Intensity, Time & Type
  - Active Recovery: continue exercises at moderate pace (30-50% MaxHR) warm-up and warm-down. This helps drrive lactic acid out faster than inactivity.

** Chapter 2: SEAL Mission-Related Physical Activities
Not Relevant to me.

** Chapter 3: Cardiorespiratory Conditioning
ACSM recommendation: “Every US adult should accumulate 30 minutes or more of moderate intensity physical activity on most, preferably all, days of the week”

- Basically, we want to train the body/heart to get oxygen from lung into blood, then pumps it to muscle to be used. do it faster, and also sustain it for a longer time.
- Maximal Oxygen Uptake (VO2max) is best predictor for sustained work performance. typical values are from 30 ml [unfit] to 80 ml [very fit] (of oxygen)/(body weight)kg/min.
- Anaerobic threshold: Usually at around 60-100% of VO2Max. Most people can only sustain non-oxygen working stage for no more than a few minutes.
- Work rate: the rate of amount of work we can do in an exercise. for example, In cycling the unit is miles per hour. Other exercise can be kcal or watts per hour.

** Chapter 4: Running for fitness
- Navy Seals should maintain running 20 to 40 miles (32 to 64) miles per week. (6 to 12 km, 5 days per week)
- Running Shoes Terminology and how to buy: read more in PDF
- Building up Our Mileage. Increasing to quickly can cause injuries.
  - Run at least 3 to 4 times per week or every other day. (with 1-2 rest days per week)
  - Run at an even pace that we can talk comfortably.
  - when we can run continuously for 40 minutes, then start thinking about increasing distance.
  - increase mileage by no more than 20% a week.
