---
title: Presentation Summary - Learned Optimism
subtitle: None
description: None
tags: economics
created: 2016-08-17
published: 2016-08-17
status: finished
confidence: log
importance: 1
---

Presentation is [[https://github.com/raganwald/presentations/blob/master/optimism.md][here]].

Optimism is the way we explain things that happened to us. There is no one "correct" way, since they are just different interpretations from the same information/situation.

The difference between being optimistic and pessimistic is that, in the former you will give yourself **more chance to become better.**

** 3-Axis of explanations
*** Impersonal vs Personal
They don't like my work because of me.

vs

They don't like my work because it lacks some features they want.

*** General vs Specific 
They don't like my work because it probably sucks at everything.

vs
 
They don't like my work because it probably lacks feature A.

*** Permanent vs Temporary 

They don't like my work, a guy told me on that day.

vs

People always hate my work my whole life, and its not going to change.

*** How to give the best chance for yourself? Do this, learned optimism:

/Optimistic praise/ (good things that happened) should be *personal*, *general*, and *permanent*.

#+BEGIN_QUOTE
"This issue you filed shows why *you* have been and will *continue* to be an *asset* to the community."
#+END_QUOTE

/Optimistic criticism/ (bad things that happened) should be *impersonal*, *specific*, and *temporary*.

#+BEGIN_QUOTE
"*This* pull request does not currently meet *our* *current* standards,
because these *specific* A, B and C reasons."
#+END_QUOTE
\\

\\

